name: Native Image Build

on:
  push:
    branches:
      - master


jobs:
  verify:
    name: Verify project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Verify with Maven
        run: mvn --batch-mode --update-snapshots verify


  build-with-jpackage:
    needs: verify
    name: Build on ${{ matrix.os.name }} with jpackage ${{ matrix.os.maven-profile }}
    runs-on: ${{ matrix.os.name }}
    strategy:
      matrix:
        os: [
          { name: ubuntu-latest, binary-file-name: "fx-demo_0.0.1_amd64.deb", release-name: "fx-demo_0.0.1_amd64.deb", maven-profile: "-P linux-deb" },
          { name: ubuntu-latest, binary-file-name: "demo.zip", release-name: "PublicDemoName-linux-image.zip", maven-profile: "-P app-image" },
          { name: windows-latest, binary-file-name: "PublicDemoName-0.0.1.exe", release-name: "PublicDemoName-setup.exe", maven-profile: "-P windows-exe" }
        ]
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: |
          mvn -P jpackage ${{ matrix.os.maven-profile }} --batch-mode --update-snapshots clean compile javafx:jlink jpackage:jpackage

      - name: zip target app-image
        if: contains(matrix.os.maven-profile, 'app-image')
        run: |
          pushd target/dist
          zip -r demo.zip PublicDemoName
          popd

      - name: Upload binary to release
        uses: svenstaro/upload-release-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/dist/${{ matrix.os.binary-file-name }}
          asset_name: ${{ matrix.os.release-name }}
          overwrite: true
          tag: jpackage
          release_name: native image with jpackage
